module Asn1
  class Reader
    @bytes: String
    @cursor: Integer
    @header_length: Integer
    @tag: Integer

    attr_reader tag: Integer
    attr_reader length: Integer

    def enumerate_content_bytes: -> Enumerator[Integer]

    def eoc?: -> bool

    def read_header: -> void

    def read_next_object: -> Reader

    def read_sequence: -> Reader
    def read_object_identifier: -> String

    def total_length: -> Integer

    private

    def length_is_short_form: (first_length_byte: Integer) -> bool
    def read_length: -> Integer

    def skip_parsed_bytes: -> void
  end
end
